services:

  app:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - database

  database:
    image: mysql
    
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=go_reserv
      - MYSQL_USER=apiDev
      - MYSQL_PASSWORD=password

volumes:
  db-data:
